# Site settings
title: Rafa Garcia-Lepper
email: rafael.g.lepper@gmail.com
url: http://rafagarcialepper.com
role: Front-end engineer
phone: 07833463308
description: "Front-end engineer specialising in writing modular, responsive, maintainable and scalable web systems"

# Footer settings
footer: Rafa Garcia-Lepper

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rglepper
  - title: linkedin
    url: https://www.linkedin.com/in/rafaelgarcialepper/
  - title: stackoverflow
    url: http://stackoverflow.com/users/1159471/rglepper
  - title: github
    url: https://github.com/rglepper

# Build settings
markdown: kramdown
permalink: pretty
sass:
    sass_dir: _sass

defaults:
    path: "assets/img"
    values:
      image: true